services:
  backend:
    build: ./app/backend
    image: marine-backend
    ports:
      - "8000:8000"
    volumes:
      - ./app/backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@localhost:5432/marinedata
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=marinedata
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:  
